skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
q3_26_vault = "F6KToxk45SdWpXrEPNEFhnXKa3PU8vc79DqXT4bB74qP"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
